- name: Deploy to EC2
  hosts: localhost
  connection: local

  tasks:
    - name: Locate running EC2 instances
      vars:
        ansible_python_interpreter: /usr/local/bin/python3
      ec2_instance_info:
        region: us-east-1
        aws_access_key: ASIAWT6NTPIZIT46345J
        aws_secret_key: dgSVwAjjkLK/GtLrnrd/edkvFV0mcLJpfC0oGeCQ
        security_token: FwoGZXIvYXdzEJr//////////wEaDCqYN2SOMs0ThwEUjiLIAQJ2pRYzxvMT0EotecA7QKKhFhXtm9RYbROHqTrP8+1IZwWDRzjPROShRS8Nwk06itP2ZrdvwlqZlsW0ALYe0xAGcjUPHidQOHTCmBxeUMLrsy2Nff2y5DdKrQYoH8DaKKqBGaRRa3U3JKeD9Hve0C7Hzwne4nbH64i2RPjxm86UUG09Lne6eBUfHoCU5nNumzdu23gyFGx6auHGN1eewnv5yPBJngNRVn6oq4VaM89IJF2K3QrKDcW59dUY8GyllfhLAnw7kX7mKJSL7v4FMi28fQhjFDANJEyfB+r1uU/hpuJ79OmIbbgzMKd2ftt8qkrRjG4Kw1lbGzvSAwg=
      register: ec2_info

    - name: Launch EC2 instance
      ec2:
        instance_type: t2.small
        image: ami-085925f297f89fce1
        region: us-east-1
        key_name: test
        vpc_subnet_id: subnet-693ebd48
        assign_public_ip: yes
        wait: yes
        count: 1
        group: eshop
        aws_access_key: ASIAWT6NTPIZIT46345J
        aws_secret_key: dgSVwAjjkLK/GtLrnrd/edkvFV0mcLJpfC0oGeCQ
        security_token: FwoGZXIvYXdzEJr//////////wEaDCqYN2SOMs0ThwEUjiLIAQJ2pRYzxvMT0EotecA7QKKhFhXtm9RYbROHqTrP8+1IZwWDRzjPROShRS8Nwk06itP2ZrdvwlqZlsW0ALYe0xAGcjUPHidQOHTCmBxeUMLrsy2Nff2y5DdKrQYoH8DaKKqBGaRRa3U3JKeD9Hve0C7Hzwne4nbH64i2RPjxm86UUG09Lne6eBUfHoCU5nNumzdu23gyFGx6auHGN1eewnv5yPBJngNRVn6oq4VaM89IJF2K3QrKDcW59dUY8GyllfhLAnw7kX7mKJSL7v4FMi28fQhjFDANJEyfB+r1uU/hpuJ79OmIbbgzMKd2ftt8qkrRjG4Kw1lbGzvSAwg=

      register: ec2

    - name: Add instance host to group
      add_host: hostname={{ item.public_dns_name }} groupname=launched
      with_items: '{{ec2.instances}}'

    - name: Wait for SSH connection
      wait_for: host={{ item.public_dns_name }} port=22 delay=30 timeout=300 state=started
      with_items: '{{ec2.instances}}'

- name: Configure EC2
  hosts: launched
  connection: ssh

  tasks:
    - name: Install docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
      become: yes
    - service:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: Get project files from docker
      git:
        repo: "https://github.com/krystofkomanec/4IT572_semestralka.git"
        dest: ./app
    - name: Build docker with eshop
      shell: cd app && docker build -t myeshop:latest .
      become: yes
    - name: Run docker with eshop
      shell: docker run -p 80:3000 myeshop
      async: 120
      poll: 0
      become: yes
    - wait_for:
        port: 80

- name: Terminate previous instances
  hosts: localhost
  connection: local

  tasks:
    - name: Terminate previous instances
      ec2:
        region: us-east-1
        state: 'absent'
        instance_ids: '{{ item.instance_id }}'
        aws_access_key: ASIAWT6NTPIZIT46345J
        aws_secret_key: dgSVwAjjkLK/GtLrnrd/edkvFV0mcLJpfC0oGeCQ
        security_token: FwoGZXIvYXdzEJr//////////wEaDCqYN2SOMs0ThwEUjiLIAQJ2pRYzxvMT0EotecA7QKKhFhXtm9RYbROHqTrP8+1IZwWDRzjPROShRS8Nwk06itP2ZrdvwlqZlsW0ALYe0xAGcjUPHidQOHTCmBxeUMLrsy2Nff2y5DdKrQYoH8DaKKqBGaRRa3U3JKeD9Hve0C7Hzwne4nbH64i2RPjxm86UUG09Lne6eBUfHoCU5nNumzdu23gyFGx6auHGN1eewnv5yPBJngNRVn6oq4VaM89IJF2K3QrKDcW59dUY8GyllfhLAnw7kX7mKJSL7v4FMi28fQhjFDANJEyfB+r1uU/hpuJ79OmIbbgzMKd2ftt8qkrRjG4Kw1lbGzvSAwg=

      loop: "{{ ec2_info.instances }}"
      loop_control:
        label: "{{ item.instance_id }}"
